In [3]:
# Imports.
import numpy as np

## Arrays and multiplication

In [6]:
# Vectors.
a = np.array([1,2,3,4])
print(a.shape)

# ||a||_2^2
print("Squared inner product:")
print(a @ a)

print("Entry-wise multiplication:")
print(a * a)

(4,)
Squared inner product:
30
Entry-wise multiplication:
[ 1  4  9 16]


In [14]:
# Convert to 2d array.
a = a.reshape(4,1)
print(a)
print(a.shape)

print("Inner product:")
print((a.T @ a)[0][0])

print("Outer product:")
print(a @ a.T)

print("Entry-wise multiplication:")
print(a * a)

[[1]
 [2]
 [3]
 [4]]
(4, 1)
Inner product:
30
Outer product:
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]
Entry-wise multiplication:
[[ 1]
 [ 4]
 [ 9]
 [16]]


In [16]:
# Note:
a @ a

ValueError: shapes (4,1) and (4,1) not aligned: 1 (dim 1) != 4 (dim 0)

## Linear regression

In [18]:
# Generate data.
A = 100 * np.random.randn(20,5)
x = np.random.rand(5,1)
noise = np.random.randn(20,1)

# Observed data.
b = A @ x + noise

In [16]:
# Get info about using NumPy's least-squares function.
# help(np.linalg.lstsq)

In [20]:
np.linalg.lstsq(A,b,rcond=None)

(array([[0.04684413],
        [0.02478589],
        [0.27761611],
        [0.46316196],
        [0.39160781]]),
 array([20.49312311]),
 5,
 array([545.206276  , 512.80092849, 446.32143078, 387.23866822,
        237.49152412]))

In [23]:
x_hat = np.linalg.lstsq(A,b,rcond=None)[0] # Only interested in the first output.

Norm-squared error
$$||x-\hat x||_2^2$$ 

In [24]:
error = x_hat - x

# Multiple ways to compute the same thing.
print(np.dot(error.T,error))
print(sum(error * error))
print(sum(error **2))

[[4.00555484e-05]]
[4.00555484e-05]
[4.00555484e-05]


Residual norm-squared error
$$||A \hat x - b||_2^2$$

In [25]:
# Residual error.
residual_error = A @ x_hat - b
sum(residual_error ** 2)

array([20.49312311])

In [27]:
residual_error_comparison = np.linalg.lstsq(A,b,rcond=None)[1]
print(residual_error_comparison)

[20.49312311]
