In [17]:
import numpy as np

In [18]:
def lcs(x, y):
    m = len(x)+1 
    n = len(y)+1
    table = [[None]*n for i in range(m)]

    for i in range(m):
        for j in range(n):
            if i == 0 or j == 0:
                table[i][j] = 0
            elif x[i-1] == y[j-1]:
                table[i][j] = table[i-1][j-1]+1
            else:
                table[i][j] = max(table[i-1][j], table[i][j-1])

    display(table)
    return table[m-1][n-1]

lcs("GGATCGT", "CGAGCTT")

[[0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 1, 1, 1, 1, 1],
 [0, 0, 1, 1, 2, 2, 2, 2],
 [0, 0, 1, 2, 2, 2, 2, 2],
 [0, 0, 1, 2, 2, 2, 3, 3],
 [0, 1, 1, 2, 2, 3, 3, 3],
 [0, 1, 2, 2, 3, 3, 3, 3],
 [0, 1, 2, 2, 3, 3, 4, 4]]

In [11]:
def latexify(Arr,decimal_places = 3, concise=False):
    '''
    Converts numpy arrays to Latex code.
    Courtesy of Charles Stoksik, Winter 2020.
    '''
    Arr = np.round(Arr,decimal_places) 

    #concise determines whether rows will be separated by newlines
    style = ' ' if concise else '\n'   
    
    if Arr.ndim == 1: #needed to handle vectors
        print('$$\\begin{bmatrix}')
        print(' \\\\{}'.format(style).join(map(str,Arr)))
        print('\\end{bmatrix}$$\n')
    else:
        print('\\begin{center}')
        print('\\begin{tabular}')
        print(' \\\\{}'.format(style).join([' & '.join(map(str,row)) for row in Arr]))
        print('\\end{tabular}')
        print('\\end{center}')

In [19]:
latexify(lcs("GGATCGT", "CGAGCTT"))

\begin{center}
\begin{tabular}
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 1 & 1 & 1 & 1 & 1 & 1 \\
0 & 0 & 1 & 1 & 2 & 2 & 2 & 2 \\
0 & 0 & 1 & 2 & 2 & 2 & 2 & 2 \\
0 & 0 & 1 & 2 & 2 & 2 & 3 & 3 \\
0 & 1 & 1 & 2 & 2 & 3 & 3 & 3 \\
0 & 1 & 2 & 2 & 3 & 3 & 3 & 3 \\
0 & 1 & 2 & 2 & 3 & 3 & 4 & 4
\end{tabular}
\end{center}


In [41]:
def knapsack(vals, costs, B):
    n = len(vals)+1
    table = [[None for R in range(0, B+1, 5)] for k in range(n)]

    for k in range(n):
        for R in range(0, B+1, 5):
            if k == 0 or R == 0:
                table[k][R//5] = 0
            elif costs[k-1] <= R:
                table[k][R//5] = max(table[k-1][(R-costs[k-1])//5] + vals[k-1], table[k-1][R//5])
            else:
                table[k][R//5] = table[k-1][R//5]

    display(table)
    return table[n-1][B//5]

t = [5, 10, 20, 25, 35]
p = [4, 3, 17, 20, 30]
knapsack(p, t, 50)

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
 [0, 4, 4, 7, 7, 7, 7, 7, 7, 7, 7],
 [0, 4, 4, 7, 17, 21, 21, 24, 24, 24, 24],
 [0, 4, 4, 7, 17, 21, 24, 24, 27, 37, 41],
 [0, 4, 4, 7, 17, 21, 24, 30, 34, 37, 41]]

41

In [38]:
latexify(knapsack(p, t, 50))

\begin{center}
\begin{tabular}
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
0 & 4 & 4 & 4 & 4 & 4 & 4 & 4 & 4 & 4 & 4 \\
0 & 4 & 4 & 7 & 7 & 7 & 7 & 7 & 7 & 7 & 7 \\
0 & 4 & 4 & 7 & 17 & 21 & 21 & 24 & 24 & 24 & 24 \\
0 & 4 & 4 & 7 & 17 & 21 & 24 & 24 & 27 & 37 & 41 \\
0 & 4 & 4 & 7 & 17 & 21 & 24 & 30 & 34 & 37 & 41
\end{tabular}
\end{center}


In [ ]:
def viterbi(y, A, E, init):
    table = [[None]*len(y) for i in range(A.shape[0])]
    
    for i in range(table[0]):
        

    for k in range(n):
        for R in range(0, B+1, 5):
            if k == 0 or R == 0:
                table[k][R//5] = 0
            elif costs[k-1] <= R:
                table[k][R//5] = max(table[k-1][(R-costs[k-1])//5] + vals[k-1], table[k-1][R//5])
            else:
                table[k][R//5] = table[k-1][R//5]

    display(table)
    return table[n-1][B//5]

In [1]:
import numpy as np

def viterbi(y, A, E, init):
    K = A.shape[0]
    E = np.repeat(E[np.newaxis, :], K, axis=0)

    T = len(y)
    T1 = np.empty((K, T), 'd')
    T2 = np.empty((K, T), 'B')

    T1[:, 0] = init * E[:, y[0]]
    T2[:, 0] = 0

    for i in range(1, T):
        T1[:, i] = np.max(T1[:, i - 1] * A.T * E[np.newaxis, :, y[i]].T, 1)
        T2[:, i] = np.argmax(T1[:, i - 1] * A.T, 1)

    x = np.empty(T, 'B')
    x[-1] = np.argmax(T1[:, T - 1])
    for i in reversed(range(1, T)):
        x[i - 1] = T2[x[i], i]

    return x, T1, T2

y = np.array([1,0,0,0,1,0,0,1,1,1,1])
# A = np.array([[0.9, 0.1],[0.15, 0.85]])
A = np.array([[0.9, 0.15],[0.1, 0.85]])
E = np.array([0.75, 0.55])
init = np.array([1, 0])

viterbi(y, A, E, init)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8),
 array([[5.50000000e-01, 3.71250000e-01, 2.50593750e-01, 1.69150781e-01,
         8.37296367e-02, 5.65175048e-02, 3.81493157e-02, 1.88839113e-02,
         9.34753609e-03, 4.62703036e-03, 2.29038003e-03],
        [0.00000000e+00, 6.18750000e-02, 4.17656250e-02, 2.81917969e-02,
         1.39549395e-02, 9.41958413e-03, 6.35821929e-03, 3.14731855e-03,
         1.55792268e-03, 7.71171727e-04, 3.81730005e-04]]),
 array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8))

(array([1, 1, 1, 1, 1, 1], dtype=uint8),
 array([[0.25      , 0.075     , 0.0225    , 0.00826875, 0.00434109,
         0.00130233],
        [0.15      , 0.07875   , 0.04134375, 0.02170547, 0.00488373,
         0.00256396]]),
 array([[0, 0, 0, 1, 1, 0],
        [0, 1, 1, 1, 1, 1]], dtype=uint8))

In [5]:

def viterbi(y, A, E, pi):
    K = A.shape[0]
    T = len(y)
    T1 = np.empty((K, T), 'd')
    T2 = np.empty((K, T), 'B')

    T1[:, 0] = pi * E[:, y[0]]
    T2[:, 0] = 0

    for i in range(1, T):
        T1[:, i] = np.max(T1[:, i - 1] * A.T * E[np.newaxis, :, y[i]].T, 1)
        T2[:, i] = np.argmax(T1[:, i - 1] * A.T, 1)

    x = np.empty(T, 'B')
    x[-1] = np.argmax(T1[:, T - 1])
    for i in reversed(range(1, T)):
        x[i - 1] = T2[x[i], i]

    return x, T1, T2

y = np.array([1,0,0,0,1,0,0,1,1,1,1])

A = np.array([[0.9, 0.15],[0.1, 0.85]])
E = np.array([[0.75,0.25], [0.55,0.45]])
init = np.array([1, 0])

viterbi(y, A, E, init)

(array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1], dtype=uint8),
 array([[2.50000000e-01, 1.68750000e-01, 1.13906250e-01, 7.68867188e-02,
         1.72995117e-02, 1.16771704e-02, 7.88209003e-03, 1.77347026e-03,
         3.99030808e-04, 8.97819317e-05, 2.02009346e-05],
        [0.00000000e+00, 2.06250000e-02, 1.39218750e-02, 9.39726563e-03,
         5.18985352e-03, 2.42625652e-03, 1.13427492e-03, 5.32041077e-04,
         2.03505712e-04, 7.78409348e-05, 2.97741576e-05]]),
 array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1]], dtype=uint8))

In [53]:
np.empty(len(y), 'B')

array([ 0.00000000e+000, -2.68678226e+154,  2.96439388e-323,
        0.00000000e+000,  0.00000000e+000,  5.74084271e+169,
        5.89090280e-091,  3.60188547e+175,  1.00511896e-047,
        2.25078704e+184,  3.99910963e+252])

In [62]:
ans = [[5.50000000e-01, 3.71250000e-01, 2.50593750e-01, 1.69150781e-01,
         8.37296367e-02, 5.65175048e-02, 3.81493157e-02, 1.88839113e-02,
         9.34753609e-03, 4.62703036e-03, 2.29038003e-03],
        [0.00000000e+00, 4.12500000e-02, 2.78437500e-02, 1.87945313e-02,
         9.30329297e-03, 6.27972275e-03, 4.23881286e-03, 2.09821237e-03,
         1.03861512e-03, 5.14114485e-04, 2.54486670e-04]]

latexify(ans, 4)

\begin{center}
\begin{tabular}
0.55 & 0.3713 & 0.2506 & 0.1692 & 0.0837 & 0.0565 & 0.0381 & 0.0189 & 0.0093 & 0.0046 & 0.0023 \\
0.0 & 0.0412 & 0.0278 & 0.0188 & 0.0093 & 0.0063 & 0.0042 & 0.0021 & 0.001 & 0.0005 & 0.0003
\end{tabular}
\end{center}


In [69]:
ans = [[2.50000000e-01, 1.68750000e-01, 1.13906250e-01, 7.68867188e-02,
         1.72995117e-02, 1.16771704e-02, 7.88209003e-03, 1.77347026e-03,
         3.99030808e-04, 8.97819317e-05, 2.02009346e-05],
        [0.00000000e+00, 1.37500000e-02, 9.28125000e-03, 6.26484375e-03,
         3.45990234e-03, 1.61750435e-03, 7.56183282e-04, 3.54694051e-04,
         1.35670475e-04, 5.18939565e-05, 1.98494384e-05]]

latexify(ans, 6)

\begin{center}
\begin{tabular}
0.25 & 0.16875 & 0.113906 & 0.076887 & 0.0173 & 0.011677 & 0.007882 & 0.001773 & 0.000399 & 9e-05 & 2e-05 \\
0.0 & 0.01375 & 0.009281 & 0.006265 & 0.00346 & 0.001618 & 0.000756 & 0.000355 & 0.000136 & 5.2e-05 & 2e-05
\end{tabular}
\end{center}
