In [22]:
import numpy as np

In [23]:
def predictor_corrector(f, a, b, alpha, h):
    t = [a]
    w = [alpha]
    N = int((b-a)/h)
    
    for i in range(N):
        t_new = t[i]+h
        predicted_w = w[i] + h*f(t[i]+h/2, w[i] + h*f(t[i], w[i])/2)
        corrected_w = w[i] + h*f(t_new, predicted_w)/2 + h*f(t[i],w[i])/2
        t.append(t_new)
        w.append(corrected_w)
        
    return t, w

In [24]:
def fcn(t, w):
    x = np.array((w[1], 6*np.exp(-t) + 4*w[0]))
    return x

In [25]:
predictor_corrector(fcn, 0, 1, np.array((0,0)), 0.1)

([0,
  0.1,
  0.2,
  0.30000000000000004,
  0.4,
  0.5,
  0.6,
  0.7,
  0.7999999999999999,
  0.8999999999999999,
  0.9999999999999999],
 [array([0, 0]),
  array([0.02853688, 0.57745123]),
  array([0.11325143, 1.12302863]),
  array([0.25230638, 1.66401985]),
  array([0.44655915, 2.22701842]),
  array([0.69954804, 2.83904582]),
  array([1.01759112, 3.52868601]),
  array([1.41000161, 4.3272785 ]),
  array([1.88942776, 5.27021851]),
  array([2.47233084, 6.39841726]),
  array([3.17961983, 7.75998141])])