In [2]:
import numpy as np

j = np.array(((2, 1, 0), (1, -2, 0), (1, 1, 1)))

In [4]:
np.linalg.inv(j)

array([[ 0.4,  0.2,  0. ],
       [ 0.2, -0.4, -0. ],
       [-0.6,  0.2,  1. ]])

In [5]:
a = np.array((1, 1, 1))

In [6]:
f = np.array((1+1-37, 1-1-5, 1+1+1-3))

In [8]:
a-np.linalg.inv(j)*f

array([[ 15.,   2.,   1.],
       [  8.,  -1.,   1.],
       [-20.,   2.,   1.]])

In [12]:
a - np.matmul(np.linalg.inv(j), f)

array([ 16.,   6., -19.])